<?php

return [
    'quotes' => [
        'Always remember that you are absolutely unique. Just like everyone else. - Margaret Mead',
        'An unexamined life is not worth living. - Socrates',
        'Be present above all else. - Naval Ravikant',
        'Because you are alive, everything is possible. - Thich Nhat Hanh',
        'Breathing in, I calm body and mind. Breathing out, I smile. - Thich Nhat Hanh',
        'Do what you can, with what you have, where you are. - Theodore Roosevelt',
        'Happiness is not something ready-made. It comes from your own actions. - Dalai Lama',
        'He who is contented is rich. - Laozi',
        'I begin to speak only when I am certain what I will say is not better left unsaid. - Cato the Younger',
        'I have not failed. I\'ve just found 10,000 ways that won\'t work. - Thomas Edison',
        'If you do not have a consistent goal in life, you cannot live it in a consistent way. - Marcus Aurelius',
        'It always seems impossible until it is done. - Nelson Mandela',
        'It is never too late to be what you might have been. - George Eliot',
        'It is not the man who has too little, but the man who craves more, that is poor. - Seneca',
        'It is quality rather than quantity that matters. - Lucius Annaeus Seneca',
        'Knowing is not enough; we must apply. Being willing is not enough; we must do. - Leonardo da Vinci',
        'Let all your things have their places; let each part of your business have its time. - Benjamin Franklin',
        'Life is available only in the present moment. - Thich Nhat Hanh',
        'Live as if you were to die tomorrow. Learn as if you were to live forever. - Mahatma Gandhi',
        'No surplus words or unnecessary actions. - Marcus Aurelius',
        'Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less. - Maria Sklodowska-Curie',
        'Nothing worth having comes easy. - Theodore Roosevelt',
        'Order your soul. Reduce your wants. - Augustine',
        'People find pleasure in different ways. I find it in keeping my mind clear. - Marcus Aurelius',
        'Simplicity is an acquired taste. - Katharine Gerould',
        'Simplicity is the consequence of refined emotions. - Jean D\'Alembert',
        'Simplicity is the essence of happiness. - Cedric Bledsoe',
        'Simplicity is the ultimate sophistication. - Leonardo da Vinci',
        'Smile, breathe, and go slowly. - Thich Nhat Hanh',
        'The best way to take care of the future is to take care of the present moment. - Thich Nhat Hanh',
        'The biggest battle is the war against ignorance. - Mustafa Kemal Ataturk',
        'The only way to do great work is to love what you do. - Steve Jobs',
        'The whole future lies in uncertainty: live immediately. - Seneca',
        'Very little is needed to make a happy life. - Marcus Aurelius',
        'Walk as if you are kissing the Earth with your feet. - Thich Nhat Hanh',
        'Waste no more time arguing what a good man should be, be one. - Marcus Aurelius',
        'We must ship. - Taylor Otwell',
        'Well begun is half done. - Aristotle',
        'When there is no desire, all things are at peace. - Laozi',
        'You must be the change you wish to see in the world. - Mahatma Gandhi',
        'Act only according to that maxim whereby you can, at the same time, will that it should become a universal law. - Immanuel Kant',
        'Always deliver more than expected - Larry Page @ Google',
        'Be more curious - Tanner Christensen @ Facebook',
        'Complaining is not a strategy - Jeff Bezos @ Amazon',
        'Done is better than perfect - Sheryl Sandberg @ Facebook',
        'Experiment. Fail. Learn. Repeat.',
        'Get Shit Done - Aaron Levie @ Box',
        'Ideas are worthless until you get them out of your head to see what they can do - Tanner Christensen @ Facebook',
        'Less Meetings. More Doing - Jason Goldberg @ Fab.com',
        'Life is short. Do stuff that matters - Siqi Chen @ Hey',
        'Make it work then make it better',
        'Never, never, never give up - Winston Churchill',
        'Quality is the best business plan - John Lasseter @ Pixar',
        'Set goals. Reach. Repeat',
        'Start where you are, use what you have, do what you can',
        'The worst decision is indecision - Ryan Harwood @ PureWow',
        'There is only one boss... the customer - Sam Walton @ Walmart',
        'Think like a customer - Paul Gillin',
        'Try again. Fail again. Fail better - Samuel Beckett',
        'Vision without execution is hallucination',
        'Wake up with determination. Go to bed with satisfaction',
        'Whatever the problem, be part of the solution - Tina Fey',
        "Be so good they can't ignore you - Steve Martin",
        "Don't Compromise - Steve Jobs @ Apple",
        "Don't guess. Measure - Slava Akhmechet @ RethinkDB",
        "If a user is having a problem, it's our problem - Steve Jobs @ Apple",
        "It's simple until you make it complicated - Jason Fried @ Twitter",
        "Optimism, pessimism, F... that! We're going to make it happen - Elon Musk @ Tesla",
        "There are seven days in a week. Someday isn't one of them",
        "There's nothing wrong with being small. You can do big things with a small team - Jason Fried @ 37signals",
        "We have a strategic plan. It's called Doing Things - Herb Kelleher @ Southwest Airlines",
        'The best way to predict the future is to invent it. - Alan Kay',
        'People ignore design that ignores people. - Frank Chimero',
        'Make every detail perfect and limit the number of details to perfect. - Jack Dorsey @ Twitter',
        'Success is a lousy teacher. It seduces smart people into thinking they can\'t lose. - Bill Gates @ Microsoft',
        'Your most unhappy customers are your greatest source of learning. - Bill Gates @ Microsoft',
        'Don\'t compare yourself with anyone in this world. If you do so, you are insulting yourself. - Bill Gates @ Microsoft',
        'In the long run, we shape our tools and thereafter our tools shape us. - Marshall McLuhan',
        'Any sufficiently advanced technology is indistinguishable from magic. - Arthur C. Clarke',
        'The Internet is becoming the town square for the global village of tomorrow. - Bill Gates @ Microsoft',
        'Software is eating the world. - Marc Andreessen @ Andreessen Horowitz',
        'Product/market fit means being in a good market with a product that can satisfy that market. - Marc Andreessen',
        'The only thing that matters is getting to product-market fit. - Marc Andreessen',
        'Markets that don\'t exist don\'t care how smart you are. - Marc Andreessen',
        'The secret of successful hiring is this: look for the people who want to change the world. - Marc Benioff @ Salesforce',
        'Behind every problem is an opportunity. - Marc Benioff @ Salesforce',
        'You don\'t need to have a 100-person company to develop that idea. - Larry Page @ Google',
        'If you\'re changing the world, you\'re working on important things. You\'re excited to get up in the morning. - Larry Page @ Google',
        'Always work hard on something uncomfortably exciting. - Larry Page @ Google',
        'We tried to define a search engine that could understand exactly what you mean and give you back exactly what you want. - Larry Page @ Google',
        'Great things in business are never done by one person. They\'re done by a team. - Steve Jobs @ Apple',
        'Innovation distinguishes between a leader and a follower. - Steve Jobs @ Apple',
        'Design is not just what it looks like and feels like. Design is how it works. - Steve Jobs @ Apple',
        'Real artists ship. - Steve Jobs @ Apple',
        'If you really look closely, most overnight successes took a long time. - Steve Jobs @ Apple',
        'Walking on water and developing software from a specification are easy if both are frozen. - Edward V. Berard',
        'Controlling complexity is the essence of computer programming. - Brian Kernighan',
        'Debugging is twice as hard as writing the code in the first place. - Brian Kernighan',
        'Fix the cause, not the symptom. - Steve Maguire',
        'Programming isn\'t about what you know; it\'s about what you can figure out. - Chris Pine',
        'The function of good software is to make the complex appear to be simple. - Grady Booch',
        'Good code is its own best documentation. - Steve McConnell',
        'The most disastrous thing that you can ever learn is your first programming language. - Alan Kay',
        'Build something 100 people love, not something 1 million people kind of like. - Brian Chesky @ Airbnb',
        'Culture is simply a shared way of doing something with passion. - Brian Chesky @ Airbnb',
        'Airbnb didn\'t start because of a brilliant idea, but because of a problem. - Brian Chesky @ Airbnb',
        'The most important thing is to get the product right. - Evan Spiegel @ Snapchat',
        'The hardest part is deciding what to build. - Dustin Moskovitz @ Facebook/Asana',
        'Do things that don\'t scale. - Paul Graham @ Y Combinator',
        'Startups = growth. - Paul Graham @ Y Combinator',
        'Make something people want. - Paul Graham @ Y Combinator',
        'The way to get startup ideas is not to try to think of startup ideas. - Paul Graham',
        'The best startup ideas tend to have three things in common: they\'re something the founders want, that they themselves can build, and that few others realize are worth doing. - Paul Graham',
        'It\'s better to have 100 people love you than a million sort of like you. - Paul Graham',
        'You can\'t build a great company without great people. - Vinod Khosla',
        'Only the paranoid survive. - Andy Grove @ Intel',
        'Bad companies are destroyed by crisis. Good companies survive them. Great companies are improved by them. - Andy Grove @ Intel',
        'The user\'s time is your most valuable resource. - Jakob Nielsen',
        'Pay attention to what users do, not what they say. - Jakob Nielsen',
        'Usability is not a luxury. - Jakob Nielsen',
        'Design adds value faster than it adds cost. - Joel Spolsky',
        'It\'s easier to change the specification to fit the program than vice versa. - Alan Perlis',
        'Everything fails, all the time. - Werner Vogels @ Amazon',
        'You build it, you run it. - Werner Vogels @ Amazon',
        'Automation is good, so long as you know exactly where to put the machine. - Eliyahu Goldratt',
        'Growth is never by mere chance; it is the result of forces working together. - James Cash Penney',
        'Leadership is about making others better as a result of your presence and making sure that impact lasts in your absence. - Sheryl Sandberg @ Meta',
        'Ideas are easy. Execution is everything. - John Doerr @ Kleiner Perkins',
        'If you\'re not embarrassed by your product, you launched too late. - Reid Hoffman @ LinkedIn',
        'Working software is the primary measure of progress. - Agile Manifesto',
        'Responding to change over following a plan. - Agile Manifesto',
        'Simplicity—the art of maximizing the amount of work not done—is essential. - Agile Manifesto',
        'Continuous attention to technical excellence enhances agility. - Agile Manifesto',
        'All problems in computer science can be solved by another level of indirection. - David Wheeler',
        'There are only two hard things in computer science: cache invalidation and naming things. - Phil Karlton',
        'If debugging is removing bugs, programming must be adding them. - Edsger W. Dijkstra',
        'The sooner you start coding, the longer the program will take. - Roy Carlson',
        'Programming can be fun, and so can cryptography; however, they should not be combined. - Kreitzberg & Shneiderman',
    ],
];
